# Generated by Django 3.2.24 on 2024-02-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('clg_name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=100)),
                ('cgpa', models.FloatField()),
                ('clg_from', models.DateField()),
                ('clg_till', models.DateField()),
                ('school_name', models.CharField(max_length=200)),
                ('percentage', models.FloatField()),
                ('school_till', models.DateField()),
                ('project_name', models.CharField(max_length=200)),
                ('about_project', models.TextField(max_length=2000)),
                ('skills', models.TextField(max_length=2000)),
            ],
        ),
    ]
